apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ubi-cr
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - get
  - list
  - patch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - patch
  - update
