apiVersion: batch/v1
kind: Job
metadata:
  name: verify-secret-certificates
  namespace: sleep
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: Delete=false
spec:
  template:
    spec:
      containers:
      - name: verify-secret-certificates
        image: quay.io/ggomez/istio:v1 
        command:
          - /bin/bash
          - -c
          - |
            echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - Restart istio-egressgateway pods"
            oc rollout restart deploy/$(oc get deploy -l app=istio-egressgateway -n istio-system -o jsonpath={.items..metadata.name}) -n istio-system
            echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - Wait 30s for istio-egressgateway rollout to complete"
            sleep 30
            echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - Check istio SDS if certificates within the secrets are valid"
            if [[ $(istioctl pc secret "$(oc get pod -n istio-system -l app=istio-egressgateway -o jsonpath={.items[0].metadata.name})" -n istio-system | grep -i WARMING | wc -l) -ne 0 ]]
            then
              echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - There is an issue with the following certificates"
              echo "RESOURCE NAME                             TYPE           STATUS      VALID CERT     SERIAL NUMBER                        NOT AFTER                NOT BEFORE"
              istioctl pc secret "$(oc get pod -n istio-system -l app=istio-egressgateway -o jsonpath={.items[0].metadata.name})" -n istio-system | grep -i WARMING
              POD_ISTIOD=$(oc get po -l app=istiod -o jsonpath='{.items[0].metadata.name}' -n istio-system)
              echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - Check $POD_ISTIOD logs:"
              oc logs $POD_ISTIOD -n istio-system --since 5m | grep -i "invalid certificates"
              exit 1
            else
              echo "$(date +'%Y-%m-%d_%H:%M:%S.%N') - All certificates are valid"
              istioctl pc secret "$(oc get pod -n istio-system -l app=istio-egressgateway -o jsonpath={.items[0].metadata.name})" -n istio-system
            fi 
      restartPolicy: Never
      serviceAccountName: ubi
  backoffLimit: 2
