apiVersion: batch/v1
kind: Job
metadata:
  name: verify-secret-certificates
  namespace: sleep
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: Delete=false
spec:
  template:
    spec:
      containers:
      - name: verify-secret-certificates
        image: quay.io/ggomez/istio:v1 
        command:
          - /bin/bash
          - -c
          - |
            echo "Restart istio-egressgateway pods"
            oc rollout restart deploy/$(oc get deploy -l app=istio-egressgateway -n istio-system -o jsonpath={.items..metadata.name}) -n istio-system
            echo "Wait for rolout to complete"
            oc rollout status -w deploy/$(oc get deploy -l app=istio-egressgateway -n istio-system -o jsonpath={.items..metadata.name}) -n istio-system
            echo "Check istio SDS if certificates are properly loaded"
            istioctl pc secret "$(oc get pod -n istio-system -l app=istio-egressgateway -o jsonpath={.items..metadata.name})" -n istio-system
      restartPolicy: Never
      serviceAccountName: ubi
  backoffLimit: 2
